#!/bin/bash
if [ $# -lt 1 ]; then
    echo no argument
    exit
fi
hosts=(`cat /home/atguigu/bin/hosts.sh`)
for host in ${hosts[@]}; do
    echo ------- $host -------
    for file in $@;do
        if [ -e $file ]; then
            pdir=$(cd -P $(dirname $file); pwd)
            fname=$(basename $file)
            ssh $host "mkdir -p $pdir"
            rsync -av $pdir/$fname $host:$pdir
        else
            echo $file not exists
        fi
    done
done